version: '3'

services:
    web-server:
        build: web-server
        ports:
            - "80:3000"
        volumes:
            - ./web-server/logs:/var/web-server/log
            - ./scripts:/scripts
        command: ["/scripts/wait-for-it.sh", "mysql_master:3306", "--", "node", "index.js"]
        depends_on:
            - mysql_master
            - mysql_slave
    mongo_1:
        image: mongo
        volumes:
            - ./mongo1:/data
        ports:
           - "27018:27017"
        command: mongod --bind_ip 0.0.0.0 --smallfiles --replSet MySecureData
        depends_on:
            - mongo_2
            - mongo_3
    mongo_2:
        image: mongo
        volumes:
            - ./mongo2:/data
        ports:
            - "27019:27017"
        command: mongod --bind_ip 0.0.0.0 --smallfiles --replSet MySecureData
    mongo_3:
        image: mongo
        volumes:
            - ./mongo3:/data
        ports:
            - "27020:27017"
        command: mongod --bind_ip 0.0.0.0 --smallfiles --replSet MySecureData
    mongo_setup:
        image: mongo
        volumes:
            - ./scripts:/scripts
        command: ["/scripts/wait-for-it.sh", "mongo_1:27017", "--", "/scripts/initiate_replica_master.sh"]
        depends_on:
            - mongo_1
            - mongo_2
            - mongo_3
    mysql_master:
        image: bitnami/mysql:5
        volumes:
            - ./mysql_master:/bitnami
        environment:
            - MYSQL_ROOT_PASSWORD=jeanmichelmaire
            - MYSQL_REPLICATION_MODE=master
            - MYSQL_REPLICATION_USER=my_repl_userynov8795
            - MYSQL_REPLICATION_PASSWORD=my_repl_passwordingesup559g
            - MYSQL_USER=api
            - MYSQL_PASSWORD=jackjack01
            - MYSQL_DATABASE=weather_api
    mysql_slave:
        image: bitnami/mysql:5
        volumes:
            - ./mysql_slave:/bitnami
            - ./scripts:/scripts
        environment:
            - MYSQL_REPLICATION_MODE=slave
            - MYSQL_REPLICATION_USER=my_repl_userynov8795
            - MYSQL_REPLICATION_PASSWORD=my_repl_passwordingesup559g
            - MYSQL_MASTER_HOST=mysql_master
            - MYSQL_MASTER_PORT_NUMBER=3306
            - MYSQL_MASTER_ROOT_PASSWORD=jeanmichelmaire
        depends_on:
            - mysql_master
    phpmyadmin_master:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql_master
    phpmyadmin_slave:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=mysql_slave